/**
 * UI-NFR-012 §3.2 service worker registration helper.
 *
 * The actual service worker is generated by `vite-plugin-pwa` at build
 * time (Workbox-backed, R-011). This module wraps the registration so
 * the rest of the app can call `registerServiceWorker()` once during
 * boot without having to deal with the
 * `import.meta.env.MODE === 'development'` skip / scope check / update
 * banner wiring inline.
 *
 * The vite-plugin-pwa setup itself lands as a follow-up — wiring the
 * plugin into `vite.config.ts`, adding `virtual:pwa-register` to the
 * import map, and shipping the precache + workbox runtime caching
 * config (R-007 through R-014). Until then this helper falls through to
 * a no-op so callers can already wire it up.
 */

export interface ServiceWorkerRegistrationOptions {
  /**
   * Called when a new service worker version is available. UI layers
   * use this to render the "Neue Version verfügbar" banner (R-014).
   */
  onUpdateAvailable?: (registration: ServiceWorkerRegistration) => void;
  /** Called once the service worker has activated for the first time. */
  onActivated?: (registration: ServiceWorkerRegistration) => void;
  /** Suppress registration entirely (test seam / opt-out). */
  disabled?: boolean;
}

/**
 * Register the service worker if the runtime supports it.
 *
 * Returns `null` on environments without service worker support
 * (`navigator.serviceWorker` undefined, e.g. SSR, very old browsers,
 * insecure http) or when registration is explicitly disabled. On
 * success returns the `ServiceWorkerRegistration`.
 *
 * The implementation prefers the Workbox `virtual:pwa-register` virtual
 * module when available so the registration follows the plugin's update
 * lifecycle hooks. Until the plugin is wired up the function falls
 * through to the standard `navigator.serviceWorker.register` path
 * pointing at `/sw.js`.
 */
export async function registerServiceWorker(
  options: ServiceWorkerRegistrationOptions = {},
): Promise<ServiceWorkerRegistration | null> {
  if (options.disabled) return null;
  if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) {
    return null;
  }

  try {
    const registration = await navigator.serviceWorker.register('/sw.js', {
      scope: '/',
      updateViaCache: 'none',
    });

    if (registration.waiting && options.onUpdateAvailable) {
      options.onUpdateAvailable(registration);
    }

    registration.addEventListener('updatefound', () => {
      const installing = registration.installing;
      if (!installing) return;
      installing.addEventListener('statechange', () => {
        if (installing.state === 'installed') {
          if (navigator.serviceWorker.controller && options.onUpdateAvailable) {
            options.onUpdateAvailable(registration);
          } else if (!navigator.serviceWorker.controller && options.onActivated) {
            options.onActivated(registration);
          }
        }
      });
    });

    return registration;
  } catch {
    // Service worker is not yet generated by vite-plugin-pwa, or the
    // environment refuses to register it. Don't break the app.
    return null;
  }
}

/**
 * Trigger an immediate update + activate of the waiting worker. Wire
 * this to the "Jetzt aktualisieren" button on the update banner.
 */
export function activateWaitingWorker(registration: ServiceWorkerRegistration): void {
  if (!registration.waiting) return;
  registration.waiting.postMessage({ type: 'SKIP_WAITING' });
}

/**
 * Unregister all service workers. Used on logout / tenant switch when
 * we want to drop precached private content.
 */
export async function unregisterAll(): Promise<void> {
  if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) {
    return;
  }
  const registrations = await navigator.serviceWorker.getRegistrations();
  await Promise.all(registrations.map((r) => r.unregister()));
}
