apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kamerplanter.fullname" . }}-backend
  labels:
    {{- include "kamerplanter.backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  {{- if .Values.backend.strategy }}
  strategy:
    type: {{ .Values.backend.strategy.type }}
    {{- if and (eq .Values.backend.strategy.type "RollingUpdate") .Values.backend.strategy.rollingUpdate }}
    rollingUpdate:
      {{- toYaml .Values.backend.strategy.rollingUpdate | nindent 6 }}
    {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kamerplanter.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kamerplanter.backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "kamerplanter.fullname" . }}-backend-config
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.backend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.backend.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.backend.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.backend.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
