import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import Chip from '@mui/material/Chip';
import Typography from '@mui/material/Typography';
import IconButton from '@mui/material/IconButton';
import Dialog from '@mui/material/Dialog';
import useMediaQuery from '@mui/material/useMediaQuery';
import { useTheme } from '@mui/material/styles';
import DialogTitle from '@mui/material/DialogTitle';
import DialogContent from '@mui/material/DialogContent';
import DialogActions from '@mui/material/DialogActions';
import CircularProgress from '@mui/material/CircularProgress';
import AddIcon from '@mui/icons-material/Add';
import DeleteIcon from '@mui/icons-material/Delete';
import PlayArrowIcon from '@mui/icons-material/PlayArrow';
import AutoFixHighIcon from '@mui/icons-material/AutoFixHigh';
import MobileCard from '@/components/common/MobileCard';
import PageTitle from '@/components/layout/PageTitle';
import DataTable, { type Column } from '@/components/common/DataTable';
import ConfirmDialog from '@/components/common/ConfirmDialog';
import FormSelectField from '@/components/form/FormSelectField';
import { useAppDispatch, useAppSelector } from '@/store/hooks';
import { fetchWorkflows } from '@/store/slices/tasksSlice';
import { useTableUrlState } from '@/hooks/useTableState';
import { useNotification } from '@/hooks/useNotification';
import { useApiError } from '@/hooks/useApiError';
import { useForm } from 'react-hook-form';
import * as taskApi from '@/api/endpoints/tasks';
import * as activityPlanApi from '@/api/endpoints/activityPlans';
import * as speciesApi from '@/api/endpoints/species';
import type { WorkflowTemplate, Species } from '@/api/types';
import WorkflowInstantiateDialog from './WorkflowInstantiateDialog';
import WorkflowCreateDialog from './WorkflowCreateDialog';
import { kamiTasks } from '@/assets/brand/illustrations';

export default function WorkflowTemplateListPage() {
  const theme = useTheme();
  const fullScreen = useMediaQuery(theme.breakpoints.down('sm'));
  const { t } = useTranslation();
  const dispatch = useAppDispatch();
  const navigate = useNavigate();
  const notification = useNotification();
  const { handleError } = useApiError();
  const { workflows, loading } = useAppSelector((s) => s.tasks);
  const [instantiateKey, setInstantiateKey] = useState<string | null>(null);
  const [createOpen, setCreateOpen] = useState(false);
  const [deleteKey, setDeleteKey] = useState<string | null>(null);
  const [generateOpen, setGenerateOpen] = useState(false);
  const [speciesList, setSpeciesList] = useState<Species[]>([]);
  const [generating, setGenerating] = useState(false);
  const tableState = useTableUrlState({ defaultSort: { column: 'name', direction: 'asc' } });

  const generateForm = useForm<{ species_key: string }>({
    defaultValues: { species_key: '' },
  });

  useEffect(() => {
    dispatch(fetchWorkflows({}));
  }, [dispatch]);

  const handleDelete = async () => {
    if (!deleteKey) return;
    try {
      await taskApi.deleteWorkflow(deleteKey);
      notification.success(t('pages.tasks.workflowDeleted'));
      setDeleteKey(null);
      dispatch(fetchWorkflows({}));
    } catch (err) {
      handleError(err);
    }
  };

  const handleOpenGenerate = async () => {
    setGenerateOpen(true);
    generateForm.reset({ species_key: '' });
    if (speciesList.length === 0) {
      try {
        const r = await speciesApi.listSpecies(0, 500);
        setSpeciesList(r.items);
      } catch (err) {
        handleError(err);
      }
    }
  };

  const handleGenerate = async (data: { species_key: string }) => {
    if (!data.species_key) return;
    setGenerating(true);
    try {
      const result = await activityPlanApi.generatePlan({
        species_key: data.species_key,
        force_regenerate: true,
      });
      notification.success(t('pages.tasks.workflowGenerated'));
      setGenerateOpen(false);
      dispatch(fetchWorkflows({}));
      navigate(`/aufgaben/workflows/${result.workflow_template_key}`);
    } catch (err) {
      handleError(err);
    } finally {
      setGenerating(false);
    }
  };

  const columns: Column<WorkflowTemplate>[] = [
    {
      id: 'name',
      label: t('pages.tasks.workflowName'),
      render: (r) => (
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          <span>{r.name}</span>
          {r.is_system && (
            <Chip
              label={t('pages.tasks.systemWorkflow')}
              size="small"
              color="info"
              variant="outlined"
            />
          )}
          {r.auto_generated && (
            <Chip
              label={t('pages.tasks.autoGenerated')}
              size="small"
              color="secondary"
              variant="outlined"
            />
          )}
        </Box>
      ),
      searchValue: (r) => r.name,
    },
    {
      id: 'species',
      label: t('pages.tasks.speciesOrType'),
      render: (r) => r.species_name
        ? <Chip label={r.species_name} size="small" color="success" variant="outlined" />
        : r.species_compatible.length > 0
          ? <Box sx={{ display: 'flex', gap: 0.5, flexWrap: 'wrap' }}>{r.species_compatible.map((s) => <Chip key={s} label={s} size="small" variant="outlined" />)}</Box>
          : <Typography variant="caption" color="text.secondary">{t('pages.tasks.allSpecies')}</Typography>,
      searchValue: (r) => r.species_name || r.species_compatible.join(' '),
    },
    {
      id: 'plants',
      label: t('pages.tasks.assignedPlants'),
      render: (r) => r.assigned_plant_count > 0
        ? <Chip label={`${r.assigned_plant_count}`} size="small" color="primary" />
        : <Typography variant="caption" color="text.secondary">{'\u2014'}</Typography>,
      align: 'right' as const,
    },
    {
      id: 'actions',
      label: '',
      render: (r) => (
        <Box sx={{ display: 'flex', gap: 0.5 }} onClick={(e) => e.stopPropagation()}>
          <IconButton
            size="small"
            title={t('pages.tasks.instantiateWorkflow')}
            onClick={() => setInstantiateKey(r.key)}
          >
            <PlayArrowIcon fontSize="small" />
          </IconButton>
          <IconButton
            size="small"
            color="error"
            disabled={r.is_system}
            title={r.is_system ? t('pages.tasks.systemTemplateDeleteDisabled') : t('common.delete')}
            onClick={() => setDeleteKey(r.key)}
          >
            <DeleteIcon fontSize="small" />
          </IconButton>
        </Box>
      ),
    },
  ];

  return (
    <Box data-testid="workflow-template-list-page">
      <Box
        sx={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
        }}
      >
        <PageTitle title={t('pages.tasks.workflowsTitle')} />
        <Box sx={{ display: 'flex', gap: 1 }}>
          <Button
            variant="outlined"
            startIcon={<AutoFixHighIcon />}
            onClick={handleOpenGenerate}
            data-testid="generate-workflow-button"
          >
            {t('pages.tasks.generateFromSpecies')}
          </Button>
          <Button
            variant="contained"
            startIcon={<AddIcon />}
            onClick={() => setCreateOpen(true)}
            data-testid="create-workflow-button"
          >
            {t('pages.tasks.createWorkflow')}
          </Button>
        </Box>
      </Box>
      <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
        {t('pages.tasks.workflowsIntro')}
      </Typography>
      <DataTable
        columns={columns}
        rows={workflows}
        loading={loading}
        onRowClick={(r) => navigate(`/aufgaben/workflows/${r.key}`)}
        getRowKey={(r) => r.key}
        emptyMessage={t('pages.tasks.noWorkflows')}
        emptyIllustration={kamiTasks}
        tableState={tableState}
        ariaLabel={t('pages.tasks.workflowsTitle')}
        mobileCardRenderer={(r) => (
          <MobileCard
            title={r.name}
            subtitle={r.species_name || undefined}
            chips={
              <>
                {r.is_system && <Chip label={t('pages.tasks.systemWorkflow')} size="small" color="info" variant="outlined" />}
                {r.auto_generated && <Chip label={t('pages.tasks.autoGenerated')} size="small" color="secondary" variant="outlined" />}
                {r.assigned_plant_count > 0 && <Chip label={`${r.assigned_plant_count} ${t('pages.tasks.assignedPlants')}`} size="small" color="primary" />}
              </>
            }
            fields={
              r.species_compatible.length > 0 && !r.species_name
                ? [{ label: t('pages.tasks.speciesOrType'), value: r.species_compatible.join(', ') }]
                : []
            }
          />
        )}
      />
      {instantiateKey && (
        <WorkflowInstantiateDialog
          open={!!instantiateKey}
          workflowKey={instantiateKey}
          onClose={() => setInstantiateKey(null)}
          onInstantiated={() => {
            setInstantiateKey(null);
            navigate('/aufgaben/queue');
          }}
        />
      )}
      <WorkflowCreateDialog
        open={createOpen}
        onClose={() => setCreateOpen(false)}
        onCreated={() => {
          setCreateOpen(false);
          dispatch(fetchWorkflows({}));
        }}
      />
      <ConfirmDialog
        open={!!deleteKey}
        title={t('pages.tasks.deleteWorkflow')}
        message={t('common.deleteConfirm', { name: workflows.find((w) => w.key === deleteKey)?.name ?? '' })}
        onConfirm={handleDelete}
        onCancel={() => setDeleteKey(null)}
        destructive
      />

      {/* Generate from Species Dialog */}
      <Dialog fullScreen={fullScreen} open={generateOpen}
        onClose={() => setGenerateOpen(false)}
        maxWidth="sm"
        fullWidth
      >
        <DialogTitle>{t('pages.tasks.generateFromSpecies')}</DialogTitle>
        <DialogContent>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
            {t('pages.tasks.generateFromSpeciesDescription')}
          </Typography>
          <form id="generate-form" onSubmit={generateForm.handleSubmit(handleGenerate)}>
            <FormSelectField
              name="species_key"
              control={generateForm.control}
              label={t('entities.species')}
              required
              options={speciesList.map((s) => ({
                value: s.key,
                label: `${s.common_names?.[0] ?? s.scientific_name} (${s.scientific_name})`,
              }))}
            />
          </form>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setGenerateOpen(false)}>
            {t('common.cancel')}
          </Button>
          <Button
            type="submit"
            form="generate-form"
            variant="contained"
            disabled={generating}
            startIcon={generating ? <CircularProgress size={20} /> : <AutoFixHighIcon />}
          >
            {t('pages.tasks.generateButton')}
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
}
