"""v0025_dedup_auto_generated_task_templates — remove per-phase duplicate task
templates left behind by the pre-fix activity-plan generator (Issue #619).

Before the engine fix, ``ActivityPlanEngine.generate_plan`` emitted one TaskTemplate
per *phase* for every eligible activity. A generic, phaseless activity (Umpflanzen,
Abhärten, Stroh unterlegen) forbids no phase and is therefore eligible in *every*
phase, so auto-generated workflows accumulated 3-4 identical templates per activity
(e.g. strawberry "Umpflanzen" 4x). The engine now binds each activity to a single
target phase; this one-time, idempotent repair heals workflows that were already
generated on existing volumes.

Scope: only ``task_templates`` are de-duplicated, grouped per
``(workflow_template_key, activity_key or name)``. Within each group the survivor is
the template with the lowest ``sequence_order`` (tie-broken by ``_key``) — the "first"
occurrence, matching the engine's new keep-first binding. Every other member of the
group is removed together with its ``wf_contains`` (workflow → template) and
``instance_of`` (task → template) edges, exactly as ``delete_task_template`` does.

Idempotent (M-3): a re-run finds every group already collapsed to one template and
writes nothing (``changed == 0``). Dry-run (M-5): duplicates are counted without
removing anything. Irreversible (M-6): the removed duplicate rows are not retained,
so there is no honest inverse — corrections ship as a new version.
"""

from __future__ import annotations

from typing import Any

import structlog
from arango.database import StandardDatabase

from app.data_access.arango import collections as col
from app.migrations.framework.base import Migration
from app.migrations.framework.report import MigrationReport

logger = structlog.get_logger()


def _dedup_key(template: dict[str, Any]) -> tuple[str, str]:
    """Return the grouping key for a template: workflow + activity (or name).

    Auto-generated templates carry ``activity_key``; it is the stable identity of the
    underlying activity. Legacy rows without one fall back to ``name`` so a duplicated
    phaseless activity is still collapsed.
    """
    workflow = template.get("workflow_template_key") or ""
    activity = template.get("activity_key") or ""
    identity = activity or (template.get("name") or "")
    return workflow, identity


def plan_removals(templates: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Return the templates to remove — every group member except the survivor.

    Groups by ``(workflow_template_key, activity_key or name)``; keeps the member with
    the lowest ``sequence_order`` (tie-broken by ``_key``) and marks the rest for
    removal. Ungrouped singletons are never touched.
    """
    groups: dict[tuple[str, str], list[dict[str, Any]]] = {}
    for template in templates:
        groups.setdefault(_dedup_key(template), []).append(template)

    removals: list[dict[str, Any]] = []
    for members in groups.values():
        if len(members) < 2:
            continue
        ordered = sorted(members, key=lambda t: (t.get("sequence_order", 0), t.get("_key", "")))
        removals.extend(ordered[1:])
    return removals


class DedupAutoGeneratedTaskTemplatesMigration(Migration):
    version = "0025"
    name = "dedup_auto_generated_task_templates"
    description = (
        "Remove per-phase duplicate auto-generated task templates left by the pre-fix activity-plan generator (#619)."
    )
    reversible = False

    def _scan(self, db: StandardDatabase, collection: str) -> list[dict[str, Any]]:
        """Return every document of ``collection`` (empty cursor → empty list)."""
        return list(db.aql.execute(f"FOR d IN {collection} RETURN d"))

    def _remove_template(self, db: StandardDatabase, key: str) -> None:
        """Remove a template and its wf_contains / instance_of edges (AQL-only)."""
        tt_id = f"{col.TASK_TEMPLATES}/{key}"
        db.aql.execute(
            f"FOR e IN {col.WF_CONTAINS} FILTER e._to == @tt_id REMOVE e IN {col.WF_CONTAINS}",
            bind_vars={"tt_id": tt_id},
        )
        db.aql.execute(
            f"FOR e IN {col.INSTANCE_OF} FILTER e._to == @tt_id REMOVE e IN {col.INSTANCE_OF}",
            bind_vars={"tt_id": tt_id},
        )
        db.aql.execute(
            f"REMOVE {{_key: @key}} IN {col.TASK_TEMPLATES}",
            bind_vars={"key": key},
        )

    def up(self, db: StandardDatabase, *, dry_run: bool = False) -> MigrationReport:
        templates = self._scan(db, col.TASK_TEMPLATES)
        removals = plan_removals(templates)

        details = {
            "workflows_affected": len({r.get("workflow_template_key") or "" for r in removals}),
            "removed_keys": [r.get("_key") for r in removals],
        }

        if dry_run:
            logger.info(
                "dedup_auto_generated_task_templates_dry_run",
                scanned=len(templates),
                duplicates=len(removals),
            )
            return MigrationReport(
                version=self.version,
                name=self.name,
                scanned=len(templates),
                changed=0,
                dry_run=True,
                details=details,
            )

        for template in removals:
            key = template.get("_key")
            if key:
                self._remove_template(db, key)

        logger.info(
            "dedup_auto_generated_task_templates_applied",
            scanned=len(templates),
            removed=len(removals),
        )
        return MigrationReport(
            version=self.version,
            name=self.name,
            scanned=len(templates),
            changed=len(removals),
            dry_run=False,
            details=details,
        )


migration = DedupAutoGeneratedTaskTemplatesMigration()
