"""v0059 — give tasks generated by workflow instantiation the tenant they belong to.

Before #1708, ``TaskService.instantiate_workflow`` built every task without a
``tenant_key``, so each one kept the model default ``""``. Every task list filters
strictly on the caller's tenant (``ArangoTaskRepository.get_all_tasks``), so
those tasks appeared in **no** tenant's list, and the tenant-scoped usage count
(``get_workflow_usage_stats``) counted them for nobody. The code path is fixed;
this migration repairs the rows it already wrote.

* **Which rows.** A task whose ``tenant_key`` is empty or absent **and** that
  carries a ``workflow_execution_key``. Every other task creator stamps the
  tenant (manual create, care reminders, activity plans, clone, recurrence,
  actuator fallback, the tank and watering beat tasks, adding a task to an
  execution), so an unstamped task hanging off an execution can only have come
  from instantiation.
* **Where the tenant comes from.** ``WorkflowExecution`` carries no tenant; it
  belongs to the entity it runs on. The owner is resolved exactly as
  ``get_executions_for_template`` resolves it for the execution list: the
  entity's own ``tenant_key`` for a plant instance, planting run or tank, and the
  parent **site's** for a location (``Location.tenant_key`` is never written,
  #1397). The entity is the execution's; when the execution record itself is
  gone, the task's own binding — copied from the same request at instantiation —
  is used instead.
* **No guessing.** A task whose owner cannot be resolved — entity deleted, an
  entity type without an owner (``generic``), an owner that is itself empty — is
  left exactly as it is, counted as ``unresolved`` in the report and logged with
  its key. Stamping it with any tenant would hand a row to someone who may not
  own it; left unstamped it stays in the state it has been in all along.
* **Idempotent (M-3):** only unstamped rows are selected, so a second run finds
  nothing left to stamp except the unresolved rows, which it again leaves alone.
* **Not reversible (M-6):** after the run, "stamped by v0059" and "stamped at
  create" are indistinguishable.
* **Dry run (M-5):** reports the plan and writes nothing.
"""

from __future__ import annotations

from typing import Any

import structlog
from arango.database import StandardDatabase

from app.data_access.arango import collections as col
from app.migrations.framework.base import Migration
from app.migrations.framework.report import MigrationReport

logger = structlog.get_logger(__name__)

#: Entity types whose own document carries the owning tenant.
_SELF_OWNED_ENTITY_COLLECTIONS: dict[str, str] = {
    "plant_instance": col.PLANT_INSTANCES,
    "planting_run": col.PLANTING_RUNS,
    "tank": col.TANKS,
}

#: At most this many unresolved task keys are named in the log line.
_LOGGED_UNRESOLVED_KEYS = 50


class BackfillInstantiatedTaskTenantKeyMigration(Migration):
    version = "0059"
    name = "backfill_instantiated_task_tenant_key"
    description = "Stamp the owning tenant on workflow-instantiated tasks that were created without one (#1708)."
    reversible = False

    #: Unstamped tasks generated from a workflow execution. ``doc.tenant_key ==
    #: null`` is also true for an absent attribute.
    _SCAN_QUERY = """
    FOR doc IN @@collection
      FILTER doc.tenant_key == null OR doc.tenant_key == ""
      FILTER doc.workflow_execution_key != null AND doc.workflow_execution_key != ""
      RETURN {
        key: doc._key,
        execution_key: doc.workflow_execution_key,
        entity_type: doc.entity_type,
        entity_key: doc.entity_key
      }
    """

    _TOTAL_QUERY = "RETURN LENGTH(@@collection)"

    @staticmethod
    def _get(db: StandardDatabase, collection: str, key: Any) -> dict[str, Any] | None:
        if not key or not isinstance(key, str) or not db.has_collection(collection):
            return None
        return db.collection(collection).get(key)

    def _resolve_owner(self, db: StandardDatabase, candidate: dict[str, Any]) -> str | None:
        """Return the tenant owning the task's entity, or ``None`` when it cannot be known."""
        execution = self._get(db, col.WORKFLOW_EXECUTIONS, candidate.get("execution_key"))
        source = execution if execution is not None else candidate
        entity_type = source.get("entity_type")
        entity_key = source.get("entity_key")

        if entity_type == "location":
            location = self._get(db, col.LOCATIONS, entity_key)
            owner_doc = self._get(db, col.SITES, location.get("site_key")) if location else None
        elif entity_type in _SELF_OWNED_ENTITY_COLLECTIONS:
            owner_doc = self._get(db, _SELF_OWNED_ENTITY_COLLECTIONS[entity_type], entity_key)
        else:
            owner_doc = None

        owner = owner_doc.get("tenant_key") if owner_doc else None
        return owner if isinstance(owner, str) and owner else None

    def _plan(self, db: StandardDatabase) -> tuple[int, list[tuple[str, str]], list[str]]:
        """Return ``(scanned, [(task key, tenant)], unresolved task keys)`` without writing."""
        if not db.has_collection(col.TASKS):
            return 0, [], []
        scanned = int(next(iter(db.aql.execute(self._TOTAL_QUERY, bind_vars={"@collection": col.TASKS})), 0))
        stamps: list[tuple[str, str]] = []
        unresolved: list[str] = []
        for candidate in db.aql.execute(self._SCAN_QUERY, bind_vars={"@collection": col.TASKS}):
            owner = self._resolve_owner(db, candidate)
            if owner is None:
                unresolved.append(str(candidate["key"]))
            else:
                stamps.append((str(candidate["key"]), owner))
        return scanned, stamps, unresolved

    def up(self, db: StandardDatabase, *, dry_run: bool = False) -> MigrationReport:
        scanned, stamps, unresolved = self._plan(db)

        if not dry_run and stamps:
            target = db.collection(col.TASKS)
            for key, tenant_key in stamps:
                target.update({"_key": key, "tenant_key": tenant_key}, silent=True)

        if unresolved:
            logger.warning(
                "backfill_instantiated_task_tenant_key_unresolved",
                unresolved=len(unresolved),
                task_keys=unresolved[:_LOGGED_UNRESOLVED_KEYS],
            )
        logger.info(
            "backfill_instantiated_task_tenant_key",
            scanned=scanned,
            stamped=len(stamps),
            unresolved=len(unresolved),
            dry_run=dry_run,
        )
        return MigrationReport(
            version=self.version,
            name=self.name,
            scanned=scanned,
            changed=0 if dry_run else len(stamps),
            dry_run=dry_run,
            details={
                "candidates": len(stamps) + len(unresolved),
                "stamped": len(stamps),
                "unresolved": len(unresolved),
            },
        )


migration = BackfillInstantiatedTaskTenantKeyMigration()
