"""Generate MkDocs fact-table snippets from backend code and seed data.

Standalone pre-build script, modelled on ``scripts/docs/gen_catalog.py``. It
reads the *authoritative* sources for three tables that used to be hand-kept in
the docs (and therefore drifted from the code — docs audit pattern M-3) and
writes deterministic Markdown table snippets into ``docs/_generated/``, one file
per table and locale (``.de.md`` / ``.en.md``).

Sources
-------
* ``CARE_STYLE_PRESETS`` and ``FAMILY_CARE_MAP`` in
  ``src/backend/app/domain/engines/care_reminder_engine.py`` — parsed via the
  Python AST (no import of the backend package, so the script runs in the plain
  docs toolchain without pydantic/app dependencies).
* ``src/backend/app/migrations/seed_data/starter_kits.yaml`` — parsed as YAML.

The numeric/enumerated *facts* (intervals, winter factors, active months,
watering method, auto style, difficulty, environment) come straight from those
sources, so they can never drift again. Purely editorial presentation data that
is not in the code — the human-readable style labels, the typical-plant
examples and the German/English family common names — lives in the
``*_META`` tables below (the doc-side equivalent of the frontend ``enums.*``
translations).

The generated files are ``.gitignored`` and must be regenerated before every
docs build. ``task docs:build`` / ``task docs:serve`` depend on
``task docs:fact-tables`` which runs this script.

The script fails loudly (``FactTableError``, non-zero exit) whenever a source
gains an entry that has no presentation metadata here, so a code change can
never silently drop a row or ship an untranslated one.
"""

from __future__ import annotations

import ast
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml

# ── Source locations (relative to the repo root) ───────────────────────
ENGINE_SOURCE = Path("src/backend/app/domain/engines/care_reminder_engine.py")
STARTER_KITS_SOURCE = Path("src/backend/app/migrations/seed_data/starter_kits.yaml")
OUTPUT_DIR = Path("docs/_generated")

LOCALES = ("de", "en")

GENERATED_HEADER = "<!-- generated by scripts/docs/gen_fact_tables.py — do not edit -->"


class FactTableError(RuntimeError):
    """Raised when a source cannot be parsed or lacks presentation metadata."""


# ── Localised vocabularies ─────────────────────────────────────────────

MONTH_NAMES: dict[str, tuple[str, ...]] = {
    "de": (
        "Januar", "Februar", "März", "April", "Mai", "Juni",
        "Juli", "August", "September", "Oktober", "November", "Dezember",
    ),
    "en": (
        "January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December",
    ),
}

WATERING_METHOD_LABELS: dict[str, dict[str, str]] = {
    "SOAK": {"de": "Tauchen", "en": "Soak"},
    "DRENCH_AND_DRAIN": {"de": "Durchgießen", "en": "Drench & drain"},
    "TOP_WATER": {"de": "Von oben gießen", "en": "Top watering"},
    "BOTTOM_WATER": {"de": "Von unten gießen", "en": "Bottom watering"},
}

DIFFICULTY_LABELS: dict[str, dict[str, str]] = {
    "beginner": {"de": "Einsteiger", "en": "Beginner"},
    "intermediate": {"de": "Mittelstufe", "en": "Intermediate"},
    "advanced": {"de": "Fortgeschritten", "en": "Advanced"},
}

SITE_TYPE_LABELS: dict[str, dict[str, str]] = {
    "windowsill": {"de": "Fensterbrett", "en": "Windowsill"},
    "indoor": {"de": "Innenraum", "en": "Indoors"},
    "balcony": {"de": "Balkon", "en": "Balcony"},
    "outdoor": {"de": "Außen", "en": "Outdoors"},
    "greenhouse": {"de": "Gewächshaus", "en": "Greenhouse"},
    "grow_tent": {"de": "Growzelt", "en": "Grow Tent"},
}


@dataclass(frozen=True)
class StyleMeta:
    """Editorial presentation data for one care-style preset."""

    group: str  # "indoor" | "outdoor"
    label_de: str
    label_en: str
    typical_de: str
    typical_en: str
    # Optional verbatim cell overrides (used for the freely-adjustable `custom`
    # style, whose preset numbers are just starting points).
    interval_de: str | None = None
    interval_en: str | None = None
    factor_de: str | None = None
    factor_en: str | None = None
    method_de: str | None = None
    method_en: str | None = None


#: Care-style presentation metadata, in display order. Indoor styles are shown
#: with a friendly label plus code; outdoor styles use the bare code (matching
#: the established doc layout). Every ``CareStyleType`` in the engine must have
#: an entry here or generation fails.
CARE_STYLE_META: dict[str, StyleMeta] = {
    # ── Indoor / houseplant styles ──
    "tropical": StyleMeta(
        "indoor", "Tropisch", "Tropical",
        "Monstera, Philodendron, Ficus", "Monstera, Philodendron, Ficus",
    ),
    "succulent": StyleMeta(
        "indoor", "Sukkulente", "Succulent",
        "Echeveria, Haworthia, Aloe", "Echeveria, Haworthia, Aloe",
    ),
    "orchid": StyleMeta(
        "indoor", "Orchidee", "Orchid",
        "Phalaenopsis, Dendrobium", "Phalaenopsis, Dendrobium",
    ),
    "calathea": StyleMeta(
        "indoor", "Calathea", "Calathea",
        "Calathea, Maranta, Ctenanthe", "Calathea, Maranta, Ctenanthe",
    ),
    "herb_tropical": StyleMeta(
        "indoor", "Tropische Kräuter", "Tropical Herbs",
        "Basilikum, Minze, Koriander", "Basil, Mint, Coriander",
    ),
    "mediterranean": StyleMeta(
        "indoor", "Mediterran", "Mediterranean",
        "Rosmarin, Lavendel, Thymian", "Rosemary, Lavender, Thyme",
    ),
    "fern": StyleMeta(
        "indoor", "Farn", "Fern",
        "Nephrolepis, Adiantum, Asplenium", "Nephrolepis, Adiantum, Asplenium",
    ),
    "cactus": StyleMeta(
        "indoor", "Kaktus", "Cactus",
        "Kakteen (Cactaceae)", "Cacti (Cactaceae)",
    ),
    "custom": StyleMeta(
        "indoor", "Benutzerdefiniert", "Custom",
        "—", "—",
        interval_de="Startwert 7 Tage, frei änderbar",
        interval_en="Starts at 7 days, freely adjustable",
        factor_de="Startwert 1,5×, frei änderbar",
        factor_en="Starts at 1.5×, freely adjustable",
        method_de="Frei wählbar",
        method_en="Freely selectable",
    ),
    # ── Outdoor / field styles ──
    "outdoor_annual_veg": StyleMeta(
        "outdoor", "Freiland-Gemüse (einjährig)", "Outdoor vegetables (annual)",
        "Freiland-Gemüse (einjährig)", "Outdoor vegetables (annual)",
    ),
    "outdoor_perennial": StyleMeta(
        "outdoor", "Stauden", "Perennials",
        "Stauden", "Perennials",
    ),
    "outdoor_annual_ornamental": StyleMeta(
        "outdoor", "Zierpflanzen (einjährig)", "Ornamentals (annual)",
        "Stiefmütterchen, Geranie, Lobelie", "Pansy, geranium, lobelia",
    ),
    "fruit_tree": StyleMeta(
        "outdoor", "Obstbaum", "Fruit tree",
        "Apfel, Birne, Kirsche", "Apple, pear, cherry",
    ),
    "berry_shrub": StyleMeta(
        "outdoor", "Beerenstrauch", "Berry shrub",
        "Himbeere, Johannisbeere, Stachelbeere", "Raspberry, currant, gooseberry",
    ),
    "rose": StyleMeta(
        "outdoor", "Rose", "Rose",
        "Beet-, Strauch- und Kletterrosen", "Bed, shrub, and climbing roses",
    ),
    "frost_tender_tuber": StyleMeta(
        "outdoor", "Frostempfindliche Knolle", "Frost-tender tuber",
        "Dahlie, Gladiole, Canna", "Dahlia, gladiolus, canna",
    ),
    "frost_tender_container": StyleMeta(
        "outdoor", "Frostempfindlicher Kübel", "Frost-tender container",
        "Oleander, Zitrus, Olive", "Oleander, citrus, olive",
    ),
    "winter_vegetable": StyleMeta(
        "outdoor", "Wintergemüse", "Winter vegetable",
        "Grünkohl, Feldsalat, Winterportulak", "Kale, lamb's lettuce, winter purslane",
    ),
    "spring_bulb": StyleMeta(
        "outdoor", "Frühjahrszwiebel", "Spring bulb",
        "Tulpe, Narzisse, Krokus", "Tulip, daffodil, crocus",
    ),
}

#: German/English common names for the botanical families in ``FAMILY_CARE_MAP``.
#: Every family key in the engine must have an entry here or generation fails.
FAMILY_COMMON_NAMES: dict[str, dict[str, str]] = {
    "Araceae": {"de": "Aronstabgewächse", "en": "arums"},
    "Marantaceae": {"de": "Marantengewächse", "en": "prayer plants"},
    "Orchidaceae": {"de": "Orchideen", "en": "orchids"},
    "Cactaceae": {"de": "Kakteengewächse", "en": "cacti"},
    "Crassulaceae": {"de": "Dickblattgewächse", "en": "stonecrops"},
    "Asphodelaceae": {"de": "Affodillgewächse", "en": "asphodels"},
    "Polypodiaceae": {"de": "Tüpfelfarngewächse", "en": "polypody ferns"},
    "Lamiaceae": {"de": "Lippenblütengewächse", "en": "mints"},
    "Oleaceae": {"de": "Ölbaumgewächse", "en": "olive family"},
    "Moraceae": {"de": "Maulbeergewächse", "en": "fig family"},
    "Violaceae": {"de": "Veilchengewächse", "en": "violets"},
    "Primulaceae": {"de": "Primelgewächse", "en": "primroses"},
    "Geraniaceae": {"de": "Storchschnabelgewächse", "en": "geraniums"},
    "Campanulaceae": {"de": "Glockenblumengewächse", "en": "bellflowers"},
    "Balsaminaceae": {"de": "Balsaminengewächse", "en": "balsams"},
}


# ── AST extraction of the engine constants ─────────────────────────────


def _enum_value(node: ast.expr) -> str:
    """Resolve an enum reference like ``CareStyleType.TROPICAL`` to ``tropical``.

    The engine's ``StrEnum`` values are the lower-cased member names, so we can
    recover the string value without importing the enum.
    """
    if isinstance(node, ast.Attribute):
        return node.attr.lower()
    raise FactTableError(f"expected an enum reference, got {ast.dump(node)}")


def _literal(node: ast.expr) -> object:
    """Evaluate a constant/list literal or return an enum member name."""
    if isinstance(node, ast.Constant):
        return node.value
    if isinstance(node, (ast.List, ast.Tuple)):
        return [_literal(elt) for elt in node.elts]
    if isinstance(node, ast.Attribute):
        # e.g. WateringMethod.TOP_WATER -> "TOP_WATER"
        return node.attr
    if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.USub):
        return -_literal(node.operand)  # type: ignore[operator]
    raise FactTableError(f"unsupported literal node: {ast.dump(node)}")


def _find_assignment(module: ast.Module, name: str) -> ast.Dict:
    for stmt in module.body:
        targets = (
            stmt.targets
            if isinstance(stmt, ast.Assign)
            else [stmt.target]
            if isinstance(stmt, ast.AnnAssign)
            else []
        )
        for target in targets:
            if isinstance(target, ast.Name) and target.id == name:
                value = stmt.value
                if not isinstance(value, ast.Dict):
                    raise FactTableError(f"{name} is not a dict literal")
                return value
    raise FactTableError(f"assignment to {name} not found in engine source")


def _parse_care_style_presets(module: ast.Module) -> dict[str, dict[str, object]]:
    dict_node = _find_assignment(module, "CARE_STYLE_PRESETS")
    presets: dict[str, dict[str, object]] = {}
    for key_node, value_node in zip(dict_node.keys, dict_node.values):
        if key_node is None:
            raise FactTableError("unexpected dict unpacking in CARE_STYLE_PRESETS")
        style = _enum_value(key_node)
        if not isinstance(value_node, ast.Dict):
            raise FactTableError(f"preset {style} is not a dict literal")
        fields: dict[str, object] = {}
        for fk, fv in zip(value_node.keys, value_node.values):
            if not isinstance(fk, ast.Constant) or not isinstance(fk.value, str):
                raise FactTableError(f"preset {style} has a non-string field key")
            fields[fk.value] = _literal(fv)
        presets[style] = fields
    return presets


def _parse_family_care_map(module: ast.Module) -> dict[str, str]:
    dict_node = _find_assignment(module, "FAMILY_CARE_MAP")
    mapping: dict[str, str] = {}
    for key_node, value_node in zip(dict_node.keys, dict_node.values):
        if not isinstance(key_node, ast.Constant) or not isinstance(key_node.value, str):
            raise FactTableError("FAMILY_CARE_MAP has a non-string family key")
        mapping[key_node.value] = _enum_value(value_node)
    return mapping


# ── Formatting helpers ─────────────────────────────────────────────────


def _format_factor(value: object, locale: str) -> str:
    text = f"{float(value):.1f}×"
    return text.replace(".", ",") if locale == "de" else text


def _format_interval(days: object, locale: str) -> str:
    n = int(days)  # type: ignore[arg-type]
    return f"Alle {n} Tage" if locale == "de" else f"Every {n} days"


def _format_active_months(months: object, locale: str) -> str:
    names = MONTH_NAMES[locale]
    values = [int(m) for m in months]  # type: ignore[union-attr]
    if not values:
        return "—"
    ordered = sorted(values)
    is_contiguous = ordered == list(range(ordered[0], ordered[-1] + 1))
    if is_contiguous and len(ordered) > 1:
        return f"{names[ordered[0] - 1]}–{names[ordered[-1] - 1]}"
    return ", ".join(names[m - 1] for m in ordered)


def _table(header: list[str], aligns: list[str], rows: list[list[str]]) -> str:
    lines = [
        GENERATED_HEADER,
        "",
        "| " + " | ".join(header) + " |",
        "|" + "|".join(aligns) + "|",
    ]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    lines.append("")
    return "\n".join(lines)


# ── Table renderers ────────────────────────────────────────────────────


def _validate_style_coverage(presets: dict[str, dict[str, object]]) -> None:
    missing = sorted(set(presets) - set(CARE_STYLE_META))
    if missing:
        raise FactTableError(
            "CARE_STYLE_PRESETS gained styles without presentation metadata in "
            f"CARE_STYLE_META: {missing}. Add label/typical-plant entries."
        )
    stale = sorted(set(CARE_STYLE_META) - set(presets))
    if stale:
        raise FactTableError(
            f"CARE_STYLE_META has entries not present in CARE_STYLE_PRESETS: {stale}"
        )


def _style_key_cell(style: str, meta: StyleMeta, locale: str) -> str:
    if meta.group == "indoor":
        label = meta.label_de if locale == "de" else meta.label_en
        return f"{label} (`{style}`)"
    return f"`{style}`"


def _render_indoor(presets: dict[str, dict[str, object]], locale: str) -> str:
    header = (
        ["Pflegestil", "Gießintervall (Sommer)", "Winter-Faktor", "Gießmethode", "Typische Pflanzen"]
        if locale == "de"
        else ["Care Style", "Watering Interval (Summer)", "Winter Factor", "Watering Method", "Typical Plants"]
    )
    aligns = ["---"] * 5
    rows: list[list[str]] = []
    for style, meta in CARE_STYLE_META.items():
        if meta.group != "indoor":
            continue
        preset = presets[style]
        interval = (
            (meta.interval_de if locale == "de" else meta.interval_en)
            or _format_interval(preset["watering_interval_days"], locale)
        )
        factor = (
            (meta.factor_de if locale == "de" else meta.factor_en)
            or _format_factor(preset["winter_watering_multiplier"], locale)
        )
        method = (
            (meta.method_de if locale == "de" else meta.method_en)
            or WATERING_METHOD_LABELS[str(preset["watering_method"])][locale]
        )
        typical = meta.typical_de if locale == "de" else meta.typical_en
        rows.append([_style_key_cell(style, meta, locale), interval, factor, method, typical])
    return _table(header, aligns, rows)


def _render_outdoor(presets: dict[str, dict[str, object]], locale: str) -> str:
    header = (
        ["Pflegestil", "Gießintervall (Sommer)", "Winter-Faktor", "Düngung aktiv", "Typische Pflanzen"]
        if locale == "de"
        else ["Care Style", "Watering Interval (Summer)", "Winter Factor", "Fertilizing Active", "Typical Plants"]
    )
    aligns = ["---"] * 5
    rows: list[list[str]] = []
    for style, meta in CARE_STYLE_META.items():
        if meta.group != "outdoor":
            continue
        preset = presets[style]
        rows.append(
            [
                _style_key_cell(style, meta, locale),
                _format_interval(preset["watering_interval_days"], locale),
                _format_factor(preset["winter_watering_multiplier"], locale),
                _format_active_months(preset["fertilizing_active_months"], locale),
                meta.typical_de if locale == "de" else meta.typical_en,
            ]
        )
    return _table(header, aligns, rows)


def _render_family_map(family_map: dict[str, str], locale: str) -> str:
    missing = sorted(set(family_map) - set(FAMILY_COMMON_NAMES))
    if missing:
        raise FactTableError(
            "FAMILY_CARE_MAP gained families without a common name in "
            f"FAMILY_COMMON_NAMES: {missing}."
        )
    header = ["Familie", "Auto-Stil"] if locale == "de" else ["Family", "Auto Style"]
    aligns = ["---", "---"]
    rows = [
        [f"{family} ({FAMILY_COMMON_NAMES[family][locale]})", f"`{style}`"]
        for family, style in family_map.items()
    ]
    return _table(header, aligns, rows)


def _render_starter_kits(kits: list[dict], locale: str) -> str:
    header = (
        ["Starter-Kit", "Schwierigkeit", "Umgebung"]
        if locale == "de"
        else ["Starter Kit", "Difficulty", "Environment"]
    )
    aligns = ["---", ":---:", ":---:"]
    rows: list[list[str]] = []
    for kit in kits:
        name = kit["name_i18n"][locale]
        difficulty_key = kit["difficulty"]
        site_key = kit["site_type"]
        if difficulty_key not in DIFFICULTY_LABELS:
            raise FactTableError(f"unknown difficulty {difficulty_key!r} in starter kits")
        if site_key not in SITE_TYPE_LABELS:
            raise FactTableError(f"unknown site_type {site_key!r} in starter kits")
        rows.append(
            [
                name,
                DIFFICULTY_LABELS[difficulty_key][locale],
                SITE_TYPE_LABELS[site_key][locale],
            ]
        )
    return _table(header, aligns, rows)


# ── Driver ─────────────────────────────────────────────────────────────


def _load_starter_kits(repo_root: Path) -> list[dict]:
    path = repo_root / STARTER_KITS_SOURCE
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    kits = data.get("starter_kits") or []
    if not kits:
        raise FactTableError(f"{path}: no starter_kits declared")
    return sorted(kits, key=lambda k: k["sort_order"])


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> int:
    repo_root = Path(__file__).resolve().parents[2]
    try:
        engine_module = ast.parse(
            (repo_root / ENGINE_SOURCE).read_text(encoding="utf-8"),
            filename=str(ENGINE_SOURCE),
        )
        presets = _parse_care_style_presets(engine_module)
        family_map = _parse_family_care_map(engine_module)
        _validate_style_coverage(presets)
        kits = _load_starter_kits(repo_root)
    except (FactTableError, OSError, yaml.YAMLError) as exc:
        print(f"[gen_fact_tables] error: {exc}", file=sys.stderr)
        return 2

    out_dir = repo_root / OUTPUT_DIR
    for locale in LOCALES:
        _write(out_dir / f"care-style-presets-indoor.{locale}.md", _render_indoor(presets, locale))
        _write(out_dir / f"care-style-presets-outdoor.{locale}.md", _render_outdoor(presets, locale))
        _write(out_dir / f"family-care-map.{locale}.md", _render_family_map(family_map, locale))
        _write(out_dir / f"starter-kits.{locale}.md", _render_starter_kits(kits, locale))

    print(
        f"[gen_fact_tables] wrote care-style presets "
        f"({sum(1 for m in CARE_STYLE_META.values() if m.group == 'indoor')} indoor / "
        f"{sum(1 for m in CARE_STYLE_META.values() if m.group == 'outdoor')} outdoor), "
        f"{len(family_map)} family mappings, {len(kits)} starter kits "
        f"for locales {', '.join(LOCALES)}",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
