"""Top-level OpenAPI tag declarations.

Every tag used by a router MUST be declared here with a description so the
generated document carries a complete top-level ``tags`` list
(spec/project/api-documentation/). ``scripts/export_openapi.py`` fails the
export when a router uses a tag that is missing from this list.
"""

OPENAPI_TAGS: list[dict[str, str]] = [
    {"name": "activities", "description": "Manual activity log entries for plants and locations."},
    {"name": "activity-plans", "description": "Generated activity plans and recurring activity templates."},
    {"name": "actuators", "description": "Actuator registration and rule-based environmental control (REQ-018)."},
    {"name": "admin-oidc", "description": "Platform administration of OIDC identity providers (REQ-023)."},
    {
        "name": "admin-harvest-indicators",
        "description": "Platform administration of the global harvest-indicator catalog (REQ-007 §4).",
    },
    {"name": "admin-pests", "description": "Platform administration of the global pest catalog (REQ-010)."},
    {"name": "admin-platform", "description": "Platform-level administration: users, tenants, status (REQ-024)."},
    {"name": "admin-recognition", "description": "Platform administration of the plant-recognition service."},
    {"name": "admin-reference-images", "description": "Curation of species reference images for recognition."},
    {"name": "admin-settings", "description": "Platform-wide settings administration."},
    {"name": "admin-weather", "description": "Platform administration of weather providers (REQ-046)."},
    {"name": "aquaponics", "description": "Aquaponics systems and fish stock management."},
    {"name": "attachments", "description": "File attachments for tasks and observations (NFR-013)."},
    {"name": "auth", "description": "Authentication: login, tokens, OAuth/OIDC flows, service accounts (REQ-023)."},
    {"name": "botanical-families", "description": "Botanical family master data (REQ-001)."},
    {"name": "calculations", "description": "Horticultural calculations: VPD, GDD, DLI and related metrics."},
    {"name": "calendar", "description": "Aggregated calendar view of tasks and events (REQ-015)."},
    {"name": "care-reminders", "description": "Care reminder presets and scheduling (REQ-022)."},
    {"name": "companion-planting", "description": "Companion-planting compatibility graph (REQ-028)."},
    {"name": "crop-rotation", "description": "Crop rotation planning per bed location (REQ-028)."},
    {"name": "cultivars", "description": "Cultivar master data (REQ-001)."},
    {"name": "cv-diagnosis", "description": "Computer-vision based plant health assessment (REQ-043)."},
    {"name": "dashboard", "description": "Dashboard metrics and personalizable panels (REQ-009, REQ-045)."},
    {"name": "diagnose", "description": "Guided plant problem diagnosis."},
    {
        "name": "diary",
        "description": "Tenant-wide plant diary overview with AI-analysis state (REQ-050).",
    },
    {"name": "enrichment", "description": "External master-data enrichment (REQ-011)."},
    {"name": "equipment", "description": "Equipment and device master data."},
    {"name": "family-relationships", "description": "Botanical family relationship graph incl. pest-risk propagation."},
    {"name": "favorites", "description": "Per-user favorites for species and other resources."},
    {"name": "feeding-events", "description": "Fish feeding events (aquaponics)."},
    {"name": "fertilizers", "description": "Fertilizer master data incl. mixing priorities (REQ-004)."},
    {"name": "fish-species", "description": "Fish species master data (aquaponics)."},
    {"name": "glossary", "description": "Glossary of horticultural terms."},
    {"name": "glossary-admin", "description": "Glossary administration."},
    {"name": "glossary-public", "description": "Public, unauthenticated glossary access."},
    {"name": "growth-phases", "description": "Growth phase definitions per species (REQ-003)."},
    {"name": "ha-publish", "description": "Publishing entities and values to Home Assistant (REQ-018)."},
    {"name": "hardiness-zones", "description": "Winter hardiness zones and traffic-light ratings."},
    {"name": "harvest", "description": "Harvest batches and harvest management (REQ-007)."},
    {"name": "health", "description": "Health and readiness probes."},
    {"name": "identification", "description": "Photo-based plant identification (N-001)."},
    {"name": "import", "description": "Master-data import (REQ-012)."},
    {"name": "inventree", "description": "Optional InvenTree inventory integration (REQ-016)."},
    {"name": "ipm", "description": "Integrated pest management: pests, treatments, karenz periods (REQ-010)."},
    {"name": "ai-assistant", "description": "AI assistant (RAG) endpoints."},
    {"name": "ai-assistant-admin", "description": "AI assistant administration."},
    {"name": "ai-assistant-public", "description": "Public, unauthenticated AI assistant access."},
    {"name": "ai-assistant-status", "description": "AI assistant service status."},
    {"name": "knowledge", "description": "Knowledge base / RAG search (optional knowledge service)."},
    {"name": "lifecycle", "description": "Plant lifecycle engine: transitions and overrides (REQ-003)."},
    {"name": "location-types", "description": "Location type master data (REQ-002)."},
    {"name": "locations", "description": "Locations within sites: beds, tents, shelves (REQ-002)."},
    {"name": "mcp", "description": "Model Context Protocol server endpoints."},
    {"name": "mode", "description": "Deployment mode information: light or full (REQ-027)."},
    {"name": "notifications", "description": "User notifications and notification-channel settings."},
    {"name": "nutrient-calculations", "description": "Nutrient mix calculations: EC targets and dosing (REQ-004)."},
    {"name": "nutrient-plans", "description": "Nutrient plans per species and phase (REQ-004)."},
    {"name": "observations", "description": "Sensor and manual observations with data provenance (REQ-005)."},
    {"name": "onboarding", "description": "Onboarding wizard state (REQ-020)."},
    {"name": "overwintering-profiles", "description": "Overwintering profiles and schedules (REQ-047)."},
    {"name": "pest-detection", "description": "Photo-based pest detection (REQ-044)."},
    {"name": "phase-sequences", "description": "Phase sequence templates (REQ-003)."},
    {"name": "phases", "description": "Plant phase state machine operations (REQ-003)."},
    {
        "name": "plant-diary",
        "description": "Diary entries of a single plant instance, run-independent (REQ-013 §4.7, REQ-050).",
    },
    {"name": "plant-instances", "description": "Individual plant instances and their lifecycle."},
    {"name": "plant-photos", "description": "Plant photo gallery (NFR-013)."},
    {"name": "planting-runs", "description": "Planting runs: grouped grow cycles (REQ-013)."},
    {"name": "post-harvest", "description": "Post-harvest processing: drying, curing (REQ-008)."},
    {"name": "print", "description": "Printable views and export documents (REQ-032)."},
    {"name": "privacy", "description": "GDPR self-service: data subject rights, Art. 15-21 (REQ-025)."},
    {"name": "profiles", "description": "Nutrient and requirement profiles per growth phase (REQ-003, REQ-004)."},
    {"name": "propagation", "description": "Propagation and genetic lineage: clones, crosses, grafts (REQ-017)."},
    {"name": "recognition", "description": "Plant recognition service endpoints."},
    {"name": "season", "description": "Season and phenology information."},
    {"name": "sites", "description": "Sites: gardens, rooms, greenhouses (REQ-002)."},
    {"name": "slots", "description": "Location slots for plant placement (REQ-002)."},
    {"name": "species", "description": "Species master data (REQ-001)."},
    {"name": "starter-kits", "description": "Starter kits for onboarding (REQ-020)."},
    {"name": "substrates", "description": "Substrate master data (REQ-019)."},
    {"name": "succession-plans", "description": "Succession sowing plans (REQ-028)."},
    {"name": "tanks", "description": "Nutrient and water tank management (REQ-014)."},
    {"name": "tasks", "description": "Task planning and completion (REQ-006)."},
    {"name": "tenant-scoped", "description": "Tenant-scoped resource endpoints under /t/{tenant_slug} (REQ-024)."},
    {"name": "tenants", "description": "Tenant and membership management (REQ-024)."},
    {"name": "user-preferences", "description": "Per-user UI preferences (REQ-021)."},
    {"name": "users", "description": "User account management (REQ-023)."},
    {"name": "watering-events", "description": "Watering events per plant and location (REQ-004)."},
    {"name": "watering-logs", "description": "Watering log history (REQ-004)."},
    {"name": "weather", "description": "Weather data and forecasts per site (REQ-046)."},
]
