import { screen, within, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, it, expect, beforeEach } from 'vitest';
import { http, HttpResponse } from 'msw';
import i18n from 'i18next';
import SpeciesWorkflowsSection from '@/pages/stammdaten/SpeciesWorkflowsSection';
import { renderWithProviders } from '../helpers';
import { server } from '../mocks/server';
import type { WorkflowTemplate } from '@/api/types';

const WF_URL = '/api/v1/t/test-tenant/tasks/workflows';

function makeWorkflow(overrides: Partial<WorkflowTemplate> = {}): WorkflowTemplate {
  return {
    key: 'wf-1',
    name: 'Tomaten-Workflow',
    description: null,
    created_by: 'user-1',
    version: '1.0',
    species_compatible: [],
    growth_system: null,
    difficulty_level: 'beginner',
    category: 'general',
    tags: [],
    is_system: false,
    auto_generated: false,
    species_key: 'sp-1',
    species_name: 'Solanum lycopersicum',
    total_duration_days: 0,
    assigned_entity_count: 0,
    target_entity_types: [],
    phase_sequence_key: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: null,
    ...overrides,
  };
}

/** Register the workflow list endpoint returning `list`. */
function listHandler(list: WorkflowTemplate[]) {
  return http.get(WF_URL, () => HttpResponse.json(list));
}

beforeEach(() => {
  i18n.changeLanguage('de');
});

describe('SpeciesWorkflowsSection — loading & empty state', () => {
  it('shows a spinner while loading and then the empty state', async () => {
    server.use(listHandler([]));
    renderWithProviders(<SpeciesWorkflowsSection speciesKey="sp-1" />);

    // The initial loading branch renders a spinner.
    expect(screen.getByRole('progressbar')).toBeInTheDocument();

    expect(await screen.findByText(i18n.t('pages.species.noWorkflows'))).toBeInTheDocument();
  });

  it('renders an error via the api-error handler when loading fails', async () => {
    server.use(http.get(WF_URL, () => HttpResponse.json({ message: 'boom' }, { status: 500 })));
    renderWithProviders(<SpeciesWorkflowsSection speciesKey="sp-1" />);

    // On error the list stays empty and the empty state is shown (loading resolved).
    expect(await screen.findByText(i18n.t('pages.species.noWorkflows'))).toBeInTheDocument();
  });
});

describe('SpeciesWorkflowsSection — populated list', () => {
  it('renders workflow cards with name, auto-generated, duration and assigned-count chips', async () => {
    server.use(
      listHandler([
        makeWorkflow({
          key: 'wf-1',
          name: 'Auto Workflow',
          auto_generated: true,
          total_duration_days: 42,
          assigned_entity_count: 3,
        }),
        makeWorkflow({ key: 'wf-2', name: 'System Workflow', is_system: true }),
      ]),
    );
    renderWithProviders(<SpeciesWorkflowsSection speciesKey="sp-1" />);

    expect(await screen.findByText('Auto Workflow')).toBeInTheDocument();
    expect(screen.getByText('System Workflow')).toBeInTheDocument();
    // auto_generated chip
    expect(screen.getByText(i18n.t('pages.tasks.autoGenerated'))).toBeInTheDocument();
    // duration chip
    expect(screen.getByText('42d')).toBeInTheDocument();
    // assigned-count chip (with click-to-navigate aria-label)
    expect(
      screen.getByLabelText(
        i18n.t('pages.species.viewWorkflowAssignments', { name: 'Auto Workflow' }),
      ),
    ).toBeInTheDocument();

    // The system workflow's delete button is disabled.
    const systemCard = screen.getByText('System Workflow').closest('.MuiCard-root') as HTMLElement;
    const deleteBtn = within(systemCard).getByTestId('DeleteIcon').closest('button');
    expect(deleteBtn).toBeDisabled();
  });

  it('navigates when the assigned-count chip is clicked', async () => {
    server.use(
      listHandler([
        makeWorkflow({ key: 'wf-1', name: 'Assigned WF', assigned_entity_count: 5 }),
      ]),
    );
    renderWithProviders(<SpeciesWorkflowsSection speciesKey="sp-1" />);

    const chip = await screen.findByLabelText(
      i18n.t('pages.species.viewWorkflowAssignments', { name: 'Assigned WF' }),
    );
    await userEvent.click(chip);
    // No crash — navigation handled by the router.
    expect(screen.getByText('Assigned WF')).toBeInTheDocument();
  });
});

describe('SpeciesWorkflowsSection — create empty workflow', () => {
  it('opens the create dialog, creates a workflow and reloads', async () => {
    let created: unknown = null;
    server.use(
      listHandler([]),
      http.post(WF_URL, async ({ request }) => {
        created = await request.json();
        return HttpResponse.json(makeWorkflow({ key: 'wf-new', name: 'Neuer Plan' }));
      }),
    );
    renderWithProviders(<SpeciesWorkflowsSection speciesKey="sp-1" />);

    await screen.findByText(i18n.t('pages.species.noWorkflows'));

    // Header "create workflow" button (AddIcon).
    const createBtn = screen.getByRole('button', { name: i18n.t('pages.species.createWorkflow') });
    await userEvent.click(createBtn);

    const dialog = await screen.findByRole('dialog');
    const input = within(dialog).getByLabelText(i18n.t('pages.tasks.workflowName'));
    await userEvent.type(input, 'Neuer Plan');

    await userEvent.click(within(dialog).getByRole('button', { name: i18n.t('common.create') }));

    await waitFor(() =>
      expect(created).toMatchObject({ name: 'Neuer Plan', species_key: 'sp-1' }),
    );
  });

  it('keeps the create button disabled until a name is entered', async () => {
    server.use(listHandler([]));
    renderWithProviders(<SpeciesWorkflowsSection speciesKey="sp-1" />);
    await screen.findByText(i18n.t('pages.species.noWorkflows'));

    await userEvent.click(
      screen.getByRole('button', { name: i18n.t('pages.species.createWorkflow') }),
    );
    const dialog = await screen.findByRole('dialog');
    expect(within(dialog).getByRole('button', { name: i18n.t('common.create') })).toBeDisabled();

    // Cancel closes the dialog.
    await userEvent.click(within(dialog).getByRole('button', { name: i18n.t('common.cancel') }));
    await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull());
  });
});

describe('SpeciesWorkflowsSection — auto-generate', () => {
  it('calls the activity-plan generator from the empty-state action', async () => {
    let generated: unknown = null;
    server.use(
      listHandler([]),
      http.post('/api/v1/activity-plans/generate', async ({ request }) => {
        generated = await request.json();
        return HttpResponse.json({
          workflow_template_key: 'wf-gen',
          name: 'Generated',
          species_name: 'Solanum',
          species_key: 'sp-1',
          auto_generated: true,
          growth_system: null,
          skill_level_filter: null,
          total_activities: 0,
          total_duration_days: 0,
          templates: [],
        });
      }),
    );
    renderWithProviders(<SpeciesWorkflowsSection speciesKey="sp-1" />);

    await screen.findByText(i18n.t('pages.species.noWorkflows'));
    // Empty-state action + header button both read "autoGenerate"; use the header one.
    const buttons = screen.getAllByRole('button', { name: i18n.t('pages.species.autoGenerate') });
    await userEvent.click(buttons[0]);

    await waitFor(() => expect(generated).toMatchObject({ species_key: 'sp-1' }));
  });

  it('surfaces a generation error through the error handler', async () => {
    server.use(
      listHandler([]),
      http.post('/api/v1/activity-plans/generate', () =>
        HttpResponse.json({ message: 'nope' }, { status: 500 }),
      ),
    );
    renderWithProviders(<SpeciesWorkflowsSection speciesKey="sp-1" />);
    await screen.findByText(i18n.t('pages.species.noWorkflows'));

    const buttons = screen.getAllByRole('button', { name: i18n.t('pages.species.autoGenerate') });
    await userEvent.click(buttons[0]);
    // Button re-enables after the failed generation settles.
    await waitFor(() => expect(buttons[0]).not.toBeDisabled());
  });
});

describe('SpeciesWorkflowsSection — duplicate', () => {
  it('opens the duplicate dialog prefilled and duplicates the workflow', async () => {
    let dupKey: string | null = null;
    server.use(
      listHandler([makeWorkflow({ key: 'wf-1', name: 'Basis' })]),
      http.post('/api/v1/t/test-tenant/tasks/workflows/:key/duplicate', ({ params }) => {
        dupKey = params.key as string;
        return HttpResponse.json(makeWorkflow({ key: 'wf-dup', name: 'Basis (Kopie)' }));
      }),
    );
    renderWithProviders(<SpeciesWorkflowsSection speciesKey="sp-1" />);

    const card = (await screen.findByText('Basis')).closest('.MuiCard-root') as HTMLElement;
    await userEvent.click(within(card).getByTestId('ContentCopyIcon').closest('button')!);

    const dialog = await screen.findByRole('dialog');
    // Prefilled with "Basis (copy)".
    const input = within(dialog).getByLabelText(i18n.t('pages.tasks.workflowName'));
    expect(input).toHaveValue(`Basis (${i18n.t('common.copy')})`);

    await userEvent.click(
      within(dialog).getByRole('button', { name: i18n.t('pages.species.duplicateWorkflow') }),
    );

    await waitFor(() => expect(dupKey).toBe('wf-1'));
  });
});

describe('SpeciesWorkflowsSection — delete', () => {
  it('confirms and deletes a workflow', async () => {
    let deletedKey: string | null = null;
    server.use(
      listHandler([makeWorkflow({ key: 'wf-1', name: 'Weg damit' })]),
      http.delete('/api/v1/t/test-tenant/tasks/workflows/:key', ({ params }) => {
        deletedKey = params.key as string;
        return new HttpResponse(null, { status: 204 });
      }),
    );
    renderWithProviders(<SpeciesWorkflowsSection speciesKey="sp-1" />);

    const card = (await screen.findByText('Weg damit')).closest('.MuiCard-root') as HTMLElement;
    await userEvent.click(within(card).getByTestId('DeleteIcon').closest('button')!);

    // ConfirmDialog appears.
    await userEvent.click(await screen.findByTestId('confirm-dialog-confirm'));

    await waitFor(() => expect(deletedKey).toBe('wf-1'));
  });
});
