import { screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, it, expect, beforeEach } from 'vitest';
import { http, HttpResponse } from 'msw';
import i18n from 'i18next';
import SuccessionPlanListPage from '@/pages/durchlaeufe/SuccessionPlanListPage';
import { renderWithProviders } from '../helpers';
import { server } from '../mocks/server';
import { mockSuccessionPlans } from '../mocks/handlers';

describe('SuccessionPlanListPage', () => {
  beforeEach(() => {
    i18n.changeLanguage('de');
  });

  it('renders the page title and create button', async () => {
    renderWithProviders(<SuccessionPlanListPage />);
    await waitFor(() => {
      expect(screen.getAllByText('Staffelanbau').length).toBeGreaterThan(0);
    });
    expect(screen.getByTestId('create-button')).toBeTruthy();
  });

  it('shows the empty state when no plans exist', async () => {
    renderWithProviders(<SuccessionPlanListPage />);
    await waitFor(() => {
      expect(screen.getByText(/kein staffelanbau angelegt/i)).toBeTruthy();
    });
  });

  describe('with a populated plan list', () => {
    beforeEach(() => {
      server.use(
        http.get('/api/v1/t/:tenant/succession-plans', () =>
          HttpResponse.json(mockSuccessionPlans),
        ),
      );
    });

    it('renders plan rows with the localized status chip', async () => {
      renderWithProviders(<SuccessionPlanListPage />);
      await waitFor(() => {
        expect(screen.getAllByText('Salat Staffelanbau').length).toBeGreaterThan(0);
      });
      // sp-1 is active, sp-2 is planned
      expect(screen.getByTestId('status-chip-sp-1').textContent).toContain('Aktiv');
      expect(screen.getByTestId('status-chip-sp-2').textContent).toContain('Geplant');
    });

    it('shows the batch progress (completed / total)', async () => {
      renderWithProviders(<SuccessionPlanListPage />);
      await waitFor(() => {
        expect(screen.getAllByText('2 / 8').length).toBeGreaterThan(0);
      });
    });

    it('opens the create dialog when the create button is clicked', async () => {
      const user = userEvent.setup();
      renderWithProviders(<SuccessionPlanListPage />);
      await user.click(await screen.findByTestId('create-button'));
      expect(await screen.findByTestId('succession-plan-dialog')).toBeTruthy();
    });

    it('opens the edit dialog when the edit action is clicked', async () => {
      const user = userEvent.setup();
      renderWithProviders(<SuccessionPlanListPage />);
      await screen.findAllByText('Salat Staffelanbau');
      await user.click(screen.getByTestId('edit-plan-sp-1'));
      expect(await screen.findByTestId('succession-plan-dialog')).toBeTruthy();
    });

    it('generates the staggered runs and previews them', async () => {
      const user = userEvent.setup();
      renderWithProviders(<SuccessionPlanListPage />);
      await screen.findAllByText('Salat Staffelanbau');

      await user.click(screen.getByTestId('generate-runs-sp-1'));

      const dialog = await screen.findByTestId('generated-runs-dialog');
      // 8 batch runs generated by the mock handler
      expect(within(dialog).getByText(/8 Staffel-Durchläufe erzeugt/i)).toBeTruthy();
      const list = await within(dialog).findByTestId('generated-runs-list');
      expect(within(list).getAllByRole('listitem').length).toBe(8);
    });
  });
});
