import { screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { http, HttpResponse } from 'msw';
import i18n from 'i18next';
import SuccessionPlanListPage from '@/pages/durchlaeufe/SuccessionPlanListPage';
import { renderWithProviders } from '../helpers';
import { server } from '../mocks/server';
import { mockSuccessionPlans } from '../mocks/handlers';

function usePlans(rows: unknown[]) {
  server.use(
    http.get('/api/v1/t/:tenant/succession-plans', () => HttpResponse.json(rows)),
  );
}

function enableMobileViewport() {
  vi.stubGlobal(
    'matchMedia',
    vi.fn().mockReturnValue({
      matches: true,
      addEventListener: vi.fn(),
      removeEventListener: vi.fn(),
      addListener: vi.fn(),
      removeListener: vi.fn(),
    } as unknown as MediaQueryList),
  );
}

describe('SuccessionPlanListPage', () => {
  beforeEach(() => {
    i18n.changeLanguage('de');
  });

  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it('renders the page title and create button', async () => {
    renderWithProviders(<SuccessionPlanListPage />);
    await waitFor(() => {
      expect(screen.getAllByText('Staffelanbau').length).toBeGreaterThan(0);
    });
    expect(screen.getByTestId('create-button')).toBeTruthy();
  });

  it('shows the empty state when no plans exist', async () => {
    renderWithProviders(<SuccessionPlanListPage />);
    await waitFor(() => {
      expect(screen.getByText(/kein staffelanbau angelegt/i)).toBeTruthy();
    });
  });

  describe('with a populated plan list', () => {
    beforeEach(() => {
      server.use(
        http.get('/api/v1/t/:tenant/succession-plans', () =>
          HttpResponse.json(mockSuccessionPlans),
        ),
      );
    });

    it('renders plan rows with the localized status chip', async () => {
      renderWithProviders(<SuccessionPlanListPage />);
      await waitFor(() => {
        expect(screen.getAllByText('Salat Staffelanbau').length).toBeGreaterThan(0);
      });
      // sp-1 is active, sp-2 is planned
      expect(screen.getByTestId('status-chip-sp-1').textContent).toContain('Aktiv');
      expect(screen.getByTestId('status-chip-sp-2').textContent).toContain('Geplant');
    });

    it('shows the batch progress (completed / total)', async () => {
      renderWithProviders(<SuccessionPlanListPage />);
      await waitFor(() => {
        expect(screen.getAllByText('2 / 8').length).toBeGreaterThan(0);
      });
    });

    it('opens the create dialog when the create button is clicked', async () => {
      const user = userEvent.setup();
      renderWithProviders(<SuccessionPlanListPage />);
      await user.click(await screen.findByTestId('create-button'));
      expect(await screen.findByTestId('succession-plan-dialog')).toBeTruthy();
    });

    it('opens the edit dialog when the edit action is clicked', async () => {
      const user = userEvent.setup();
      renderWithProviders(<SuccessionPlanListPage />);
      await screen.findAllByText('Salat Staffelanbau');
      await user.click(screen.getByTestId('edit-plan-sp-1'));
      expect(await screen.findByTestId('succession-plan-dialog')).toBeTruthy();
    });

    it('generates the staggered runs and previews them', async () => {
      const user = userEvent.setup();
      renderWithProviders(<SuccessionPlanListPage />);
      await screen.findAllByText('Salat Staffelanbau');

      await user.click(screen.getByTestId('generate-runs-sp-1'));

      const dialog = await screen.findByTestId('generated-runs-dialog');
      // 8 batch runs generated by the mock handler
      expect(within(dialog).getByText(/8 Staffel-Durchläufe erzeugt/i)).toBeTruthy();
      const list = await within(dialog).findByTestId('generated-runs-list');
      expect(within(list).getAllByRole('listitem').length).toBe(8);
    });

    it('closes the generated-runs preview dialog', async () => {
      const user = userEvent.setup();
      renderWithProviders(<SuccessionPlanListPage />);
      await screen.findAllByText('Salat Staffelanbau');

      await user.click(screen.getByTestId('generate-runs-sp-1'));
      await screen.findByTestId('generated-runs-dialog');

      await user.click(screen.getByTestId('generated-runs-close'));
      await waitFor(() =>
        expect(screen.queryByTestId('generated-runs-dialog')).toBeNull(),
      );
    });

    it('reports an error when generating runs fails', async () => {
      server.use(
        http.post('/api/v1/t/:tenant/succession-plans/:key/generate', () =>
          HttpResponse.json(
            {
              error_id: 'e1',
              error_code: 'INTERNAL_ERROR',
              message: 'boom',
              details: [],
              timestamp: '',
              path: '',
              method: '',
            },
            { status: 500 },
          ),
        ),
      );
      const user = userEvent.setup();
      renderWithProviders(<SuccessionPlanListPage />);
      await screen.findAllByText('Salat Staffelanbau');

      await user.click(screen.getByTestId('generate-runs-sp-1'));

      expect(await screen.findByText(i18n.t('errors.server'))).toBeTruthy();
      expect(screen.queryByTestId('generated-runs-dialog')).toBeNull();
    });

    it('deletes a plan through the confirm dialog', async () => {
      const user = userEvent.setup();
      renderWithProviders(<SuccessionPlanListPage />);
      await screen.findAllByText('Salat Staffelanbau');

      await user.click(screen.getByTestId('delete-plan-sp-1'));
      const confirm = await screen.findByTestId('confirm-dialog-confirm');
      await user.click(confirm);

      await waitFor(() =>
        expect(screen.queryByTestId('confirm-dialog')).toBeNull(),
      );
      expect(
        await screen.findByText(i18n.t('pages.successionPlans.planDeleted')),
      ).toBeTruthy();
    });

    it('runs the column search callbacks when the search box is used', async () => {
      const user = userEvent.setup();
      renderWithProviders(<SuccessionPlanListPage />);
      await screen.findAllByText('Salat Staffelanbau');

      // Typing a matching term exercises every column searchValue callback
      // (species, status, interval, batches) as the debounced filter runs over
      // each row; "Salat" matches sp-1's name so the row remains visible.
      const searchBox = screen
        .getByTestId('table-search-input')
        .querySelector('input')!;
      await user.type(searchBox, 'Salat');

      await waitFor(() => expect(searchBox.value).toBe('Salat'));
      expect(
        screen.getAllByText('Salat Staffelanbau').length,
      ).toBeGreaterThan(0);
    });

    it('closes the create dialog via cancel and dismisses the delete confirm', async () => {
      const user = userEvent.setup();
      renderWithProviders(<SuccessionPlanListPage />);
      await screen.findAllByText('Salat Staffelanbau');

      // Open + cancel the create dialog (exercises the onClose callback).
      await user.click(screen.getByTestId('create-button'));
      const dialog = await screen.findByTestId('succession-plan-dialog');
      await user.click(within(dialog).getByTestId('form-cancel-button'));
      await waitFor(() =>
        expect(screen.queryByTestId('succession-plan-dialog')).toBeNull(),
      );

      // Open + cancel the delete confirmation (exercises the onCancel callback).
      await user.click(screen.getByTestId('delete-plan-sp-1'));
      await user.click(await screen.findByTestId('confirm-dialog-cancel'));
      await waitFor(() =>
        expect(screen.queryByTestId('confirm-dialog')).toBeNull(),
      );
    });

    it('reports an error when deleting a plan fails', async () => {
      server.use(
        http.delete('/api/v1/t/:tenant/succession-plans/:key', () =>
          HttpResponse.json(
            {
              error_id: 'e2',
              error_code: 'INTERNAL_ERROR',
              message: 'boom',
              details: [],
              timestamp: '',
              path: '',
              method: '',
            },
            { status: 500 },
          ),
        ),
      );
      const user = userEvent.setup();
      renderWithProviders(<SuccessionPlanListPage />);
      await screen.findAllByText('Salat Staffelanbau');

      await user.click(screen.getByTestId('delete-plan-sp-1'));
      await user.click(await screen.findByTestId('confirm-dialog-confirm'));

      expect(await screen.findByText(i18n.t('errors.server'))).toBeTruthy();
    });
  });

  describe('status chips and date formatting', () => {
    it('renders every status colour variant and an em dash for missing dates', async () => {
      usePlans([
        { ...mockSuccessionPlans[0], key: 'sp-c', status: 'completed' },
        {
          ...mockSuccessionPlans[0],
          key: 'sp-x',
          status: 'cancelled',
          start_date: null,
          end_date: null,
        },
      ]);
      renderWithProviders(<SuccessionPlanListPage />);

      await waitFor(() =>
        expect(screen.getByTestId('status-chip-sp-c')).toBeTruthy(),
      );
      expect(screen.getByTestId('status-chip-sp-c').textContent).toContain(
        i18n.t('enums.successionPlanStatus.completed'),
      );
      expect(screen.getByTestId('status-chip-sp-x').textContent).toContain(
        i18n.t('enums.successionPlanStatus.cancelled'),
      );
      // Null start/end dates render as an em dash in the window column.
      expect(screen.getAllByText(/—/).length).toBeGreaterThan(0);
    });
  });

  describe('mobile viewport', () => {
    beforeEach(() => {
      enableMobileViewport();
      usePlans(mockSuccessionPlans);
    });

    it('renders mobile cards and generates runs via the mobile action', async () => {
      const user = userEvent.setup();
      renderWithProviders(<SuccessionPlanListPage />);
      await screen.findAllByText('Salat Staffelanbau');

      await user.click(await screen.findByTestId('generate-runs-mobile-sp-1'));

      const dialog = await screen.findByTestId('generated-runs-dialog');
      expect(
        within(dialog).getByText(/8 Staffel-Durchläufe erzeugt/i),
      ).toBeTruthy();
    });

    it('opens the edit dialog from the mobile action', async () => {
      const user = userEvent.setup();
      renderWithProviders(<SuccessionPlanListPage />);
      await screen.findAllByText('Salat Staffelanbau');

      const editButtons = screen.getAllByRole('button', {
        name: i18n.t('common.edit'),
      });
      await user.click(editButtons[0]);
      expect(await screen.findByTestId('succession-plan-dialog')).toBeTruthy();
    });

    it('opens the delete confirmation from the mobile action', async () => {
      const user = userEvent.setup();
      renderWithProviders(<SuccessionPlanListPage />);
      await screen.findAllByText('Salat Staffelanbau');

      const deleteButtons = screen.getAllByRole('button', {
        name: i18n.t('common.delete'),
      });
      await user.click(deleteButtons[0]);
      expect(await screen.findByTestId('confirm-dialog')).toBeTruthy();
    });
  });
});
