import { cleanup, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { http, HttpResponse } from 'msw';
import i18n from 'i18next';
import WorkflowTemplateListPage from '@/pages/aufgaben/WorkflowTemplateListPage';
import { renderWithProviders } from '../helpers';
import { server } from '../mocks/server';
import type { WorkflowTemplate } from '@/api/types';

const mockNavigate = vi.fn();
vi.mock('react-router-dom', async (orig) => {
  const actual = await orig<typeof import('react-router-dom')>();
  return { ...actual, useNavigate: () => mockNavigate };
});

const LIST_URL = '/api/v1/t/test-tenant/tasks/workflows';
const DELETE_URL = '/api/v1/t/test-tenant/tasks/workflows/:key';
const DUPLICATE_URL = '/api/v1/t/test-tenant/tasks/workflows/:key/duplicate';

function makeWorkflow(overrides: Partial<WorkflowTemplate> = {}): WorkflowTemplate {
  return {
    key: 'wf-1',
    name: 'Tomaten-Workflow',
    description: null,
    created_by: 'user-1',
    version: '1.0',
    species_compatible: [],
    growth_system: null,
    difficulty_level: 'beginner',
    category: 'general',
    tags: [],
    is_system: false,
    auto_generated: false,
    species_key: 'sp-1',
    species_name: 'Solanum lycopersicum',
    total_duration_days: 0,
    assigned_entity_count: 0,
    target_entity_types: ['plant_instance'],
    phase_sequence_key: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: null,
    ...overrides,
  };
}

function useWorkflows(rows: WorkflowTemplate[]) {
  server.use(http.get(LIST_URL, () => HttpResponse.json(rows)));
}

describe('WorkflowTemplateListPage', () => {
  beforeEach(() => {
    i18n.changeLanguage('de');
    mockNavigate.mockClear();
  });

  afterEach(() => {
    // Unmount before resetting the language: the file's afterEach runs before
    // testing-library's auto-cleanup (LIFO), so an i18n reset here would
    // otherwise re-render every still-mounted useTranslation() consumer
    // outside act(). Unmounting first makes the reset touch nothing.
    cleanup();
    i18n.changeLanguage('en');
  });

  it('renders the loaded workflow card', async () => {
    useWorkflows([makeWorkflow()]);
    renderWithProviders(<WorkflowTemplateListPage />);

    expect(await screen.findByText('Tomaten-Workflow')).toBeInTheDocument();
    expect(screen.getByTestId('create-workflow-button')).toBeInTheDocument();
  });

  it('renders rich card metadata variants', async () => {
    useWorkflows([
      makeWorkflow({
        key: 'wf-rich',
        name: 'Rich Workflow',
        species_name: '',
        species_compatible: ['Basil', 'Mint', 'Sage', 'Thyme'],
        category: 'watering',
        difficulty_level: 'advanced',
        target_entity_types: ['plant_instance', 'location', 'tank'],
        auto_generated: true,
        tags: ['spring', 'indoor'],
        assigned_entity_count: 5,
        total_duration_days: 30,
      }),
    ]);
    renderWithProviders(<WorkflowTemplateListPage />);

    expect(await screen.findByText('Rich Workflow')).toBeInTheDocument();
    // species_compatible > 3 -> shows first three + "+1"
    expect(screen.getByText('+1')).toBeInTheDocument();
    // auto_generated chip
    expect(screen.getByText(i18n.t('pages.tasks.autoGenerated'))).toBeInTheDocument();
    // tags rendered
    expect(screen.getByText('spring')).toBeInTheDocument();
  });

  it('renders the all-species hint when no species metadata is present', async () => {
    useWorkflows([
      makeWorkflow({ key: 'wf-any', name: 'Any Species', species_name: '', species_compatible: [] }),
    ]);
    renderWithProviders(<WorkflowTemplateListPage />);

    expect(await screen.findByText('Any Species')).toBeInTheDocument();
    expect(screen.getByText(i18n.t('pages.tasks.allSpecies'))).toBeInTheDocument();
  });

  it('navigates to the workflow detail when a card is activated', async () => {
    useWorkflows([makeWorkflow()]);
    const user = userEvent.setup();
    renderWithProviders(<WorkflowTemplateListPage />);

    const card = await screen.findByTestId('workflow-card-wf-1');
    await user.click(within(card).getByText('Tomaten-Workflow'));
    expect(mockNavigate).toHaveBeenCalledWith('/aufgaben/workflows/wf-1');
  });

  it('filters workflows through the search field', async () => {
    useWorkflows([
      makeWorkflow({ key: 'a', name: 'Alpha Flow' }),
      makeWorkflow({ key: 'b', name: 'Beta Flow', species_name: 'Ocimum' }),
    ]);
    const user = userEvent.setup();
    renderWithProviders(<WorkflowTemplateListPage />);

    await screen.findByText('Alpha Flow');
    await user.type(screen.getByTestId('workflow-search').querySelector('input')!, 'beta');
    await waitFor(() => expect(screen.queryByText('Alpha Flow')).not.toBeInTheDocument());
    expect(screen.getByText('Beta Flow')).toBeInTheDocument();
  });

  it('shows the empty state and the no-search-results message', async () => {
    useWorkflows([makeWorkflow({ name: 'Only One' })]);
    const user = userEvent.setup();
    renderWithProviders(<WorkflowTemplateListPage />);

    await screen.findByText('Only One');
    await user.type(screen.getByTestId('workflow-search').querySelector('input')!, 'zzz-none');
    expect(await screen.findByText(i18n.t('common.noSearchResults'))).toBeInTheDocument();
  });

  it('opens the instantiate dialog from the apply action', async () => {
    useWorkflows([makeWorkflow()]);
    const user = userEvent.setup();
    renderWithProviders(<WorkflowTemplateListPage />);

    const card = await screen.findByTestId('workflow-card-wf-1');
    await user.click(within(card).getByRole('button', { name: i18n.t('pages.tasks.applyWorkflow') }));
    expect((await screen.findAllByRole('dialog')).length).toBeGreaterThan(0);
  });

  it('opens the create dialog', async () => {
    useWorkflows([makeWorkflow()]);
    const user = userEvent.setup();
    renderWithProviders(<WorkflowTemplateListPage />);

    await screen.findByText('Tomaten-Workflow');
    await user.click(screen.getByTestId('create-workflow-button'));
    expect((await screen.findAllByRole('dialog')).length).toBeGreaterThan(0);
  });

  it('duplicates a workflow through the duplicate dialog', async () => {
    let duplicated = false;
    useWorkflows([makeWorkflow()]);
    server.use(
      http.post(DUPLICATE_URL, () => {
        duplicated = true;
        return HttpResponse.json(makeWorkflow({ key: 'wf-copy', name: 'Copy' }));
      }),
    );
    const user = userEvent.setup();
    renderWithProviders(<WorkflowTemplateListPage />);

    const card = await screen.findByTestId('workflow-card-wf-1');
    await user.click(within(card).getByRole('button', { name: i18n.t('pages.tasks.duplicateWorkflow') }));

    // Edit the prefilled name (exercises the controlled input), then submit via Enter.
    const nameInput = within(await screen.findByTestId('duplicate-workflow-name')).getByRole('textbox');
    await user.clear(nameInput);
    await user.type(nameInput, 'My Copy{Enter}');

    await waitFor(() => expect(duplicated).toBe(true));
    expect(
      await screen.findByText(i18n.t('pages.tasks.workflowDuplicated')),
    ).toBeInTheDocument();
  });

  it('closes the duplicate dialog on cancel', async () => {
    useWorkflows([makeWorkflow()]);
    const user = userEvent.setup();
    renderWithProviders(<WorkflowTemplateListPage />);

    const card = await screen.findByTestId('workflow-card-wf-1');
    await user.click(within(card).getByRole('button', { name: i18n.t('pages.tasks.duplicateWorkflow') }));
    await screen.findByTestId('duplicate-workflow-name');

    await user.click(screen.getByRole('button', { name: i18n.t('common.cancel') }));
    await waitFor(() =>
      expect(screen.queryByTestId('duplicate-workflow-name')).not.toBeInTheDocument(),
    );
  });

  it('closes the instantiate dialog with Escape', async () => {
    useWorkflows([makeWorkflow()]);
    const user = userEvent.setup();
    renderWithProviders(<WorkflowTemplateListPage />);

    const card = await screen.findByTestId('workflow-card-wf-1');
    await user.click(within(card).getByRole('button', { name: i18n.t('pages.tasks.applyWorkflow') }));
    await screen.findAllByRole('dialog');
    await user.keyboard('{Escape}');
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument());
  });

  it('closes the create dialog with Escape', async () => {
    useWorkflows([makeWorkflow()]);
    const user = userEvent.setup();
    renderWithProviders(<WorkflowTemplateListPage />);

    await screen.findByText('Tomaten-Workflow');
    await user.click(screen.getByTestId('create-workflow-button'));
    await screen.findAllByRole('dialog');
    await user.keyboard('{Escape}');
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument());
  });

  it('closes the delete confirmation on cancel without deleting', async () => {
    let deleteCalled = false;
    useWorkflows([makeWorkflow()]);
    server.use(
      http.delete(DELETE_URL, () => {
        deleteCalled = true;
        return new HttpResponse(null, { status: 204 });
      }),
    );
    const user = userEvent.setup();
    renderWithProviders(<WorkflowTemplateListPage />);

    const card = await screen.findByTestId('workflow-card-wf-1');
    await user.click(within(card).getByRole('button', { name: i18n.t('common.delete') }));
    await user.click(await screen.findByTestId('confirm-dialog-cancel'));

    await waitFor(() =>
      expect(screen.queryByTestId('confirm-dialog')).not.toBeInTheDocument(),
    );
    expect(deleteCalled).toBe(false);
  });

  it('deletes a workflow through the confirm dialog', async () => {
    let deletedKey: string | null = null;
    useWorkflows([makeWorkflow()]);
    server.use(
      http.delete(DELETE_URL, ({ params }) => {
        deletedKey = params.key as string;
        return new HttpResponse(null, { status: 204 });
      }),
    );
    const user = userEvent.setup();
    renderWithProviders(<WorkflowTemplateListPage />);

    const card = await screen.findByTestId('workflow-card-wf-1');
    await user.click(within(card).getByRole('button', { name: i18n.t('common.delete') }));
    await user.click(await screen.findByTestId('confirm-dialog-confirm'));

    await waitFor(() => expect(deletedKey).toBe('wf-1'));
    await waitFor(() =>
      expect(screen.queryByTestId('confirm-dialog')).not.toBeInTheDocument(),
    );
    expect(
      await screen.findByText(i18n.t('pages.tasks.workflowDeleted')),
    ).toBeInTheDocument();
  });

  it('shows the pending state on the confirm dialog while the delete is in flight', async () => {
    let resolveDelete: (() => void) | null = null;
    useWorkflows([makeWorkflow()]);
    server.use(
      http.delete(
        DELETE_URL,
        () =>
          new Promise<Response>((resolve) => {
            resolveDelete = () => resolve(new HttpResponse(null, { status: 204 }));
          }),
      ),
    );
    const user = userEvent.setup();
    renderWithProviders(<WorkflowTemplateListPage />);

    const card = await screen.findByTestId('workflow-card-wf-1');
    await user.click(within(card).getByRole('button', { name: i18n.t('common.delete') }));
    await user.click(await screen.findByTestId('confirm-dialog-confirm'));

    await waitFor(() =>
      expect(screen.getByTestId('confirm-dialog-confirm')).toHaveAttribute('aria-busy', 'true'),
    );
    expect(screen.getByTestId('confirm-dialog-live-region')).toHaveTextContent(
      i18n.t('common.processing'),
    );

    resolveDelete!();
    await waitFor(() =>
      expect(screen.queryByTestId('confirm-dialog')).not.toBeInTheDocument(),
    );
  });

  it('surfaces an error when the delete request fails', async () => {
    useWorkflows([makeWorkflow()]);
    server.use(
      http.delete(DELETE_URL, () => new HttpResponse(null, { status: 500 })),
    );
    const user = userEvent.setup();
    renderWithProviders(<WorkflowTemplateListPage />);

    const card = await screen.findByTestId('workflow-card-wf-1');
    await user.click(within(card).getByRole('button', { name: i18n.t('common.delete') }));
    await user.click(await screen.findByTestId('confirm-dialog-confirm'));

    expect(await screen.findByText(i18n.t('errors.server'))).toBeInTheDocument();
  });

  it('hides the delete action for a system workflow', async () => {
    useWorkflows([makeWorkflow({ is_system: true })]);
    renderWithProviders(<WorkflowTemplateListPage />);

    const card = await screen.findByTestId('workflow-card-wf-1');
    expect(
      within(card).queryByRole('button', { name: i18n.t('common.delete') }),
    ).not.toBeInTheDocument();
    // Apply + duplicate actions remain available.
    expect(
      within(card).getByRole('button', { name: i18n.t('pages.tasks.applyWorkflow') }),
    ).toBeInTheDocument();
  });
});
