on:
  push:

jobs:
  static:
    uses: nolte/gh-plumbing/.github/workflows/reusable-pre-commit.yaml@v1.1.12

  security:
    uses: nolte/gh-plumbing/.github/workflows/reusable-trivy.yaml@v1.1.12
    permissions:
      contents: read
      security-events: write
      actions: read

  chain-bench:
    uses: nolte/gh-plumbing/.github/workflows/reusable-chain-bench.yaml@v1.1.12
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
